###Q1: interval centered around mean w 8 st dev guaranteed to include at least what % of data?

In [ ]:
# Chebyschev's Theorem:
t = 8
(1-1/(t*t))*100

98.4375

###Q2: False; scaling data by quantiles does not require zscore computation first

###Q3: mtcars dataset, zscore of 18.1 mpg car is?

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('drive/MyDrive/Data Sci/mtcars.csv')
data.mpg.values[5]

18.1

In [ ]:
data

model   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2            Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  ...  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  ...  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  ...  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  ...  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  ...  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  ...  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  ...  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180  ...  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180  ...  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205  ...  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215  ...  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  ...  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66  ...  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52  ...  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65  ...  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97  ...  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150  ...  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150  ...  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245  ...  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175  ...  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66  ...  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91  ...  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113  ...  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264  ...  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175  ...  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335  ...  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109  ...  18.60   1   1     4     2

[32 rows x 12 columns]

In [ ]:
mpg = data.mpg.values
zs = (mpg-np.mean(mpg))/np.std(mpg)
zs[5]

-0.3355723336253064

In [ ]:
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler, QuantileTransformer
scaler = StandardScaler()
scaler.fit(data[['mpg']])
scaler.fit_transform(data[['mpg']])

###Q4: in the mtcars dataset, percentile of car that weights 3250 lbs?

In [ ]:
qtn = QuantileTransformer(n_quantiles=100)
qtn.fit_transform(data[['wt']])*100

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:2357: UserWarning: n_quantiles (100) is greater than the total number of samples (32). n_quantiles is set to n_samples.
  % (self.n_quantiles, n_samples))


array([[ 25.80645161],
       [ 35.48387097],
       [ 19.35483871],
       [ 48.38709677],
       [ 58.06451613],
       [ 64.51612903],
       [ 72.58064516],
       [ 45.16129032],
       [ 38.70967742],
       [ 58.06451613],
       [ 58.06451613],
       [ 90.32258065],
       [ 77.41935484],
       [ 80.64516129],
       [ 93.5483871 ],
       [100.        ],
       [ 96.77419355],
       [ 16.12903226],
       [  3.22580645],
       [  6.4516129 ],
       [ 22.58064516],
       [ 67.74193548],
       [ 51.61290323],
       [ 83.87096774],
       [ 87.09677419],
       [  9.67741935],
       [ 12.90322581],
       [  0.        ],
       [ 41.93548387],
       [ 29.03225806],
       [ 72.58064516],
       [ 32.25806452]])

In [ ]:
wt = data.wt.values
np.percentile(wt,68)

3.5240000000000005

###Q5: a finite sum of squared quanitites that depends on parameters (weights) always has minimum value? <font color = 'green'> True


###Q6: mtcars, predict mpg of car w wt = 2800 lbs

In [ ]:
v = data[['wt']].values
v[np.argmin(qtn.fit_transform(data[['wt']])*100)]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:2357: UserWarning: n_quantiles (100) is greater than the total number of samples (32). n_quantiles is set to n_samples.
  % (self.n_quantiles, n_samples))


array([1.513])

In [ ]:
x = data[['wt']]
y = data[['mpg']]
lm = linear_model.LinearRegression()
model = lm.fit(x,y)

In [ ]:
lm.predict([[2.8]])

array([[22.32060576]])

###Q7: change gradient descent code to calculate minimum sum of squared residuals

In [2]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 120
from IPython.display import HTML
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('drive/MyDrive/Data Sci/mtcars.csv')
X = df[['wt']]
y = df[['mpg']]

In [4]:
N = len(X)
N

32

In [5]:
data = np.concatenate((X.values,y.values),axis=1)

In [6]:
#hyperparamters established before the learning process begins
learning_rate = 0.01
initial_n = 0
initial_m = 0
num_iterations = 10000

In [ ]:
for i in range(0,32):
  print(i)

In [20]:
def compute_cost(n, m, data):
    #total_cost = 0
    total_cost = []
    
    # number of datapoints in training data
    N = float(len(data))
    
    # Compute sum of squared errors
    for i in range(0, len(data)):
        x = data[i, 0]
        y = data[i, 1]
        #total_cost += (y - (m * x + n)) ** 2
        total_cost.append( (y - (m * x + n)) ** 2)
        
    # Return average of squared error
    return min(total_cost) #/(2*N)

compute_cost(initial_n, initial_m, data)

0.8100000000000006

In [21]:
def step_gradient(b_current, m_current, data, alpha):
    """takes one step down towards the minima
    
    Args:
        b_current (float): current value of b
        m_current (float): current value of m
        data (np.array): array containing the training data (x,y)
        alpha (float): learning rate (a.k.a. step size)
    
    Returns:
        tuple: (b,m) new values of b,m
    Big Idea: Newton's algorithm for solving an equation such as f(x)=0
    """
    
    m_gradient = 0
    b_gradient = 0
    N = float(len(data))

    # Calculate Gradient
    for i in range(0, len(data)):
        x = data[i, 0]
        y = data[i, 1]
        m_gradient += - (2/N) * x * (y - (m_current * x + b_current))
        b_gradient += - (2/N) * (y - (m_current * x + b_current))
    
    # Update current m and b
    m_updated = m_current - alpha * m_gradient
    b_updated = b_current - alpha * b_gradient

    #Return updated parameters
    return b_updated, m_updated

def gradient_descent(data, starting_b, starting_m, learning_rate, num_iterations):
    """runs gradient descent
    
    Args:
        data (np.array): training data, containing x,y
        starting_b (float): initial value of b (random)
        starting_m (float): initial value of m (random)
        learning_rate (float): hyperparameter to adjust the step size during descent
        num_iterations (int): hyperparameter, decides the number of iterations for which gradient descent would run
    
    Returns:
        list : the first and second item are b, m respectively at which the best fit curve is obtained, the third and fourth items are two lists, which store the value of b,m as gradient descent proceeded.
    """

    # initial values
    b = starting_b
    m = starting_m
    
    # to store the cost after each iteration
    cost_graph = []
    
    # to store the value of b -> bias unit, m-> slope of line after each iteration (pred = m*x + b)
    b_progress = []
    m_progress = []
    
    # For every iteration, optimize b, m and compute its cost
    for i in range(num_iterations):
        cost_graph.append(compute_cost(b, m, data))
        b, m = step_gradient(b, m, np.array(data), learning_rate)
        b_progress.append(b)
        m_progress.append(m)
        
    return [b, m, cost_graph,b_progress,m_progress]

In [22]:
n, m, cost_graph,n_progress,m_progress = gradient_descent(data, initial_n, initial_m, learning_rate, num_iterations)

#Print optimized parameters
print ('Optimized n:', n)
print ('Optimized m:', m)

#Print error with optimized parameters
print ('Minimized cost:', compute_cost(n, m, data))

Optimized n: 36.91364116163406
Optimized m: -5.237781331439236
Minimized cost: 0.0058854666911840135


###Q9: from line of regression w mtcars data, the meaning of the intercept is? <font color=green> Not interpretable- having an X = 0 doesn't make sense in context of data


*From notes:*
* Do we need complicated algorithm from the intercept?
  * No, the regression line (given one input, one output) passes through the center of mass; 

###Q10: Slope of regression line always remains the same if we scale the data by zscores? <font color= 'green'> False