<a href="https://colab.research.google.com/github/gabbymignano/gabbymignano.github.io/blob/master/Lab_2_Work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Q1: interval centered around mean w 8 st dev guaranteed to include at least what % of data?

In [54]:
# Chebyschev's Theorem:
t = 4
(1-1/(t*t))*100

93.75

###Q2: False; scaling data by quantiles does not require zscore computation first

###Q3: mtcars dataset, zscore of 18.1 mpg car is?

In [45]:
import numpy as np
import pandas as pd

In [46]:
data = pd.read_csv('drive/MyDrive/Data Sci/mtcars.csv')
data.mpg.values[5]

18.1

In [ ]:
data

In [48]:
mpg = data.mpg.values
zs = (mpg-np.mean(mpg))/np.std(mpg)
zs[5]

-0.3355723336253064

In [ ]:
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler, QuantileTransformer
scaler = StandardScaler()
scaler.fit(data[['mpg']])
scaler.fit_transform(data[['mpg']])

###Q4: in the mtcars dataset, percentile of car that weights 3250 lbs?

In [50]:
qtn = QuantileTransformer(n_quantiles=100)
qtn.fit_transform(data[['wt']])*100

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:2357: UserWarning: n_quantiles (100) is greater than the total number of samples (32). n_quantiles is set to n_samples.
  % (self.n_quantiles, n_samples))


array([[ 25.80645161],
       [ 35.48387097],
       [ 19.35483871],
       [ 48.38709677],
       [ 58.06451613],
       [ 64.51612903],
       [ 72.58064516],
       [ 45.16129032],
       [ 38.70967742],
       [ 58.06451613],
       [ 58.06451613],
       [ 90.32258065],
       [ 77.41935484],
       [ 80.64516129],
       [ 93.5483871 ],
       [100.        ],
       [ 96.77419355],
       [ 16.12903226],
       [  3.22580645],
       [  6.4516129 ],
       [ 22.58064516],
       [ 67.74193548],
       [ 51.61290323],
       [ 83.87096774],
       [ 87.09677419],
       [  9.67741935],
       [ 12.90322581],
       [  0.        ],
       [ 41.93548387],
       [ 29.03225806],
       [ 72.58064516],
       [ 32.25806452]])

In [52]:
wt = data.wt.values
np.percentile(wt,68)

3.5240000000000005

###Q5: a finite sum of squared quanitites that depends on parameters (weights) always has minimum value? <font color = 'green'> True


###Q6: mtcars, predict mpg of car w wt = 2800 lbs

In [ ]:
v = data[['wt']].values
v[np.argmin(qtn.fit_transform(data[['wt']])*100)]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:2357: UserWarning: n_quantiles (100) is greater than the total number of samples (32). n_quantiles is set to n_samples.
  % (self.n_quantiles, n_samples))


array([1.513])

In [ ]:
x = data[['wt']]
y = data[['mpg']]
lm = linear_model.LinearRegression()
model = lm.fit(x,y)

In [ ]:
lm.predict([[2.8]])

array([[22.32060576]])

###Q7: change gradient descent code to calculate minimum sum of squared residuals
compute the sum of the square residuals for the learned optimal values of slope (m) and intercept (n) and not for the random values we use to initialize those variables in the gradient descent algorithm

In [25]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 120
from IPython.display import HTML
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [39]:
df = pd.read_csv('drive/MyDrive/Data Sci/mtcars.csv')
X = df[['wt']]
y = df[['mpg']]

In [35]:
N = len(X)
N

32

In [36]:
data = np.concatenate((X.values,y.values),axis=1)

In [40]:
#hyperparamters established before the learning process begins
learning_rate = 0.01
initial_b = 0
initial_m = 0
num_iterations = 10000

In [ ]:
for i in range(0,32):
  print(i)

In [31]:
# the average of the squared residuals.
def compute_cost(b, m, data):
    total_cost = 0
    
    # number of datapoints in training data
    N = float(len(data))
    
    # Compute sum of squared errors
    for i in range(0, len(data)):
        x = data[i, 0]
        y = data[i, 1]
        total_cost += (y - (m * x + b)) ** 2
        
    # Return sum of squared error
    return total_cost

In [41]:
def step_gradient(b_current, m_current, data, alpha):
    
    m_gradient = 0
    b_gradient = 0
    N = float(len(data))

    # Calculate Gradient
    for i in range(0, len(data)):
        x = data[i, 0]
        y = data[i, 1]
        m_gradient += - (2/N) * x * (y - (m_current * x + b_current))
        b_gradient += - (2/N) * (y - (m_current * x + b_current))
    
    # Update current m and b
    m_updated = m_current - alpha * m_gradient
    b_updated = b_current - alpha * b_gradient

    #Return updated parameters
    return b_updated, m_updated

def gradient_descent(data, starting_b, starting_m, learning_rate, num_iterations):

    # initial values
    b = starting_b
    m = starting_m
    
    # to store the cost after each iteration
    cost_graph = []
    
    # to store the value of b -> bias unit, m-> slope of line after each iteration (pred = m*x + b)
    b_progress = []
    m_progress = []
    
    # For every iteration, optimize b, m and compute its cost
    for i in range(num_iterations):
        cost_graph.append(compute_cost(b, m, data))
        b, m = step_gradient(b, m, data, learning_rate)
        b_progress.append(b)
        m_progress.append(m)
        
    return [b, m, cost_graph,b_progress,m_progress]

In [42]:
b, m, cost_graph,b_progress,m_progress = gradient_descent(data, initial_b, initial_m, learning_rate, num_iterations)

#Print optimized parameters
print ('Optimized b:', b)
print ('Optimized m:', m)

#Print error with optimized parameters
print ('Minimized cost:', compute_cost(b, m, data))

Optimized b: 37.285117303091454
Optimized m: -5.344469026915932
Minimized cost: 278.3219375435501


278.321937

###Q9: from line of regression w mtcars data, the meaning of the intercept is? <font color=green> Not interpretable- having an X = 0 doesn't make sense in context of data


*From notes:*
* Do we need complicated algorithm from the intercept?
  * No, the regression line (given one input, one output) passes through the center of mass; 

###Q10: Slope of regression line always remains the same if we scale the data by zscores? <font color= 'green'> False